source 'https://rubygems.org'

gem 'rails', '6.0.0'

gem 'aasm', '~> 4.12.0'
gem 'activerecord-import'
gem 'apipie-rails'
gem 'arproxy'
gem 'autoprefixer-rails'
gem 'aws-sdk-cloudwatch'
gem 'aws-sdk-ec2'
gem 'aws-sdk-kinesis'
gem 'aws-sdk-s3'
gem 'aws-sdk-sns'
gem 'aws-sdk-sqs'
gem 'bugsnag'
gem 'coffee-rails'
gem 'config'
gem 'countries', '~> 2.1.3'
gem 'dalli'
gem 'dalli-elasticache'
gem 'execjs'
gem 'faraday'
gem 'faraday_middleware'
gem 'google-api-client', '~> 0.28.0'
gem 'hashdiff'
gem 'hashie', '~> 2.0.5'
gem 'http_accept_language'
gem 'httpclient'
gem 'i18n-tasks', '~> 0.9'
gem 'jbuilder', '2.7.0'
gem 'jquery-rails'
gem 'kaminari'
gem 'mail'
gem 'maruku'
gem 'mime-types'
gem 'mini_racer'
gem 'money', '6.10.1'
gem 'mysql2'
