source 'https://rubygems.org'

gem 'net-sftp'
gem 'newrelic_rpm'
gem 'nokogiri'
gem 'oauth2'
gem 'omniauth'
gem 'omniauth-auth0'
gem 'paranoia'
gem 'phonelib'
gem 'pundit'
gem 'rack-contrib'
gem 'rack-cors'
gem 'rack-oauth2'
gem 'rails-i18n'
gem 'rails_autolink'
gem 'redis', '~> 4.1'
gem 'redis-namespace'
gem 'redis-queue'
gem 'retryable'
gem 'rmagick'
gem 'rubyzip'
gem 'sassc-rails'
gem 'savon'
gem 'scientist'
gem 'sidekiq', '< 6'
gem 'sidekiq-cron'
gem 'sidekiq-unique-jobs'
gem 'sidekiq-worker-killer'
gem 'sitemap_generator'
gem 'sprockets'
gem 'switch_point'
gem 'twilio-ruby', '~> 4.9.0'
gem 'uglifier'
gem 'unicorn'
gem 'unicorn-rails'
gem 'unicorn-worker-killer'
gem 'yajl-ruby'
