source 'https://rubygems.org'

gem 'net-sftp'
gem 'newrelic_rpm'
gem 'nokogiri'
gem 'oauth2'
gem 'omniauth'
gem 'omniauth-auth0'
gem 'paranoia'
gem 'phonelib'
gem 'pundit'
gem 'rack-contrib'
gem 'rack-cors'
gem 'rack-oauth2'
gem 'rails-i18n'
gem 'rails_autolink'
gem 'redis', '~> 4.1'
gem 'redis-namespace'
gem 'redis-queue'
gem 'retryable'
gem 'rmagick'
