jobs:
  bundle_install:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - v4-bundle-{{ checksum "Gemfile.lock" }}
      - run:
          command: bundle install --clean --jobs=4 --path=vendor/bundle
          name: bundle install
      - save_cache:
          key: v4-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
version: 2.1
workflows:
  test:
    jobs:
      - bundle_install
